package my.erp.org.vo;

import java.io.Serializable;

import my.erp.org.util.BaseVo;

/**
 * Database Table Remarks:
 *   专业信息表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table res_major
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class MajorVo extends BaseVo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_major.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   专业名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_major.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   系别
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_major.profession_id
     *
     * @mbg.generated
     */
    private String professionId;

    /**
     * Database Column Remarks:
     *   专业总人数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_major.num
     *
     * @mbg.generated
     */
    private Integer num;
    
    /**
     * 院系名称
     */
    private String professionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table res_major
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_major.id
     *
     * @return the value of res_major.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_major.id
     *
     * @param id the value for res_major.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_major.name
     *
     * @return the value of res_major.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_major.name
     *
     * @param name the value for res_major.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_major.profession_id
     *
     * @return the value of res_major.profession_id
     *
     * @mbg.generated
     */
    public String getProfessionId() {
        return professionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_major.profession_id
     *
     * @param professionId the value for res_major.profession_id
     *
     * @mbg.generated
     */
    public void setProfessionId(String professionId) {
        this.professionId = professionId == null ? null : professionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_major.num
     *
     * @return the value of res_major.num
     *
     * @mbg.generated
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_major.num
     *
     * @param num the value for res_major.num
     *
     * @mbg.generated
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_major
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", professionId=").append(professionId);
        sb.append(", num=").append(num);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

	public String getProfessionName() {
		return professionName;
	}

	public void setProfessionName(String professionName) {
		this.professionName = professionName;
	}
}