package my.erp.org.vo;

import java.io.Serializable;

import my.erp.org.util.BaseVo;

/**
 * Database Table Remarks:
 *   学生信息表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table res_student
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class StudentVo extends BaseVo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_student.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     * Database Column Remarks:
     *   姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_student.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   性别
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_student.sex
     *
     * @mbg.generated
     */
    private String sex;

    /**
     * Database Column Remarks:
     *   年龄
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_student.age
     *
     * @mbg.generated
     */
    private Integer age;

    /**
     * Database Column Remarks:
     *   生日
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_student.birthday
     *
     * @mbg.generated
     */
    private String birthday;

    /**
     * Database Column Remarks:
     *   籍贯
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_student.roots
     *
     * @mbg.generated
     */
    private String roots;

    /**
     * Database Column Remarks:
     *   民族
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_student.volk
     *
     * @mbg.generated
     */
    private String volk;

    /**
     * Database Column Remarks:
     *   学号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_student.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     * Database Column Remarks:
     *   身份证号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_student.id_card
     *
     * @mbg.generated
     */
    private String idCard;

    /**
     * Database Column Remarks:
     *   政治面貌
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_student.political
     *
     * @mbg.generated
     */
    private String political;

    /**
     * Database Column Remarks:
     *   家庭地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_student.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     * Database Column Remarks:
     *   联系方式
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_student.tel
     *
     * @mbg.generated
     */
    private String tel;

    /**
     * Database Column Remarks:
     *   邮箱
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_student.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     * Database Column Remarks:
     *   监护人联系方式
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_student.parent_tel
     *
     * @mbg.generated
     */
    private String parentTel;

    /**
     * Database Column Remarks:
     *   监护人1
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_student.parent_name1
     *
     * @mbg.generated
     */
    private String parentName1;

    /**
     * Database Column Remarks:
     *   监护人2
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_student.parent_name2
     *
     * @mbg.generated
     */
    private String parentName2;

    /**
     * Database Column Remarks:
     *   所在学校
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_student.school
     *
     * @mbg.generated
     */
    private String school;

    /**
     * Database Column Remarks:
     *   专业
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_student.major
     *
     * @mbg.generated
     */
    private String major;

    /**
     * Database Column Remarks:
     *   年级
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_student.grade
     *
     * @mbg.generated
     */
    private String grade;

    /**
     * Database Column Remarks:
     *   班级
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_student.clazz
     *
     * @mbg.generated
     */
    private String clazz;

    /**
     * Database Column Remarks:
     *   备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_student.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_student.profession
     *
     * @mbg.generated
     */
    private String profession;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table res_student
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_student.id
     *
     * @return the value of res_student.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_student.id
     *
     * @param id the value for res_student.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_student.name
     *
     * @return the value of res_student.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_student.name
     *
     * @param name the value for res_student.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_student.sex
     *
     * @return the value of res_student.sex
     *
     * @mbg.generated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_student.sex
     *
     * @param sex the value for res_student.sex
     *
     * @mbg.generated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_student.age
     *
     * @return the value of res_student.age
     *
     * @mbg.generated
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_student.age
     *
     * @param age the value for res_student.age
     *
     * @mbg.generated
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_student.birthday
     *
     * @return the value of res_student.birthday
     *
     * @mbg.generated
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_student.birthday
     *
     * @param birthday the value for res_student.birthday
     *
     * @mbg.generated
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday == null ? null : birthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_student.roots
     *
     * @return the value of res_student.roots
     *
     * @mbg.generated
     */
    public String getRoots() {
        return roots;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_student.roots
     *
     * @param roots the value for res_student.roots
     *
     * @mbg.generated
     */
    public void setRoots(String roots) {
        this.roots = roots == null ? null : roots.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_student.volk
     *
     * @return the value of res_student.volk
     *
     * @mbg.generated
     */
    public String getVolk() {
        return volk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_student.volk
     *
     * @param volk the value for res_student.volk
     *
     * @mbg.generated
     */
    public void setVolk(String volk) {
        this.volk = volk == null ? null : volk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_student.code
     *
     * @return the value of res_student.code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_student.code
     *
     * @param code the value for res_student.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_student.id_card
     *
     * @return the value of res_student.id_card
     *
     * @mbg.generated
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_student.id_card
     *
     * @param idCard the value for res_student.id_card
     *
     * @mbg.generated
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_student.political
     *
     * @return the value of res_student.political
     *
     * @mbg.generated
     */
    public String getPolitical() {
        return political;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_student.political
     *
     * @param political the value for res_student.political
     *
     * @mbg.generated
     */
    public void setPolitical(String political) {
        this.political = political == null ? null : political.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_student.address
     *
     * @return the value of res_student.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_student.address
     *
     * @param address the value for res_student.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_student.tel
     *
     * @return the value of res_student.tel
     *
     * @mbg.generated
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_student.tel
     *
     * @param tel the value for res_student.tel
     *
     * @mbg.generated
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_student.email
     *
     * @return the value of res_student.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_student.email
     *
     * @param email the value for res_student.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_student.parent_tel
     *
     * @return the value of res_student.parent_tel
     *
     * @mbg.generated
     */
    public String getParentTel() {
        return parentTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_student.parent_tel
     *
     * @param parentTel the value for res_student.parent_tel
     *
     * @mbg.generated
     */
    public void setParentTel(String parentTel) {
        this.parentTel = parentTel == null ? null : parentTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_student.parent_name1
     *
     * @return the value of res_student.parent_name1
     *
     * @mbg.generated
     */
    public String getParentName1() {
        return parentName1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_student.parent_name1
     *
     * @param parentName1 the value for res_student.parent_name1
     *
     * @mbg.generated
     */
    public void setParentName1(String parentName1) {
        this.parentName1 = parentName1 == null ? null : parentName1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_student.parent_name2
     *
     * @return the value of res_student.parent_name2
     *
     * @mbg.generated
     */
    public String getParentName2() {
        return parentName2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_student.parent_name2
     *
     * @param parentName2 the value for res_student.parent_name2
     *
     * @mbg.generated
     */
    public void setParentName2(String parentName2) {
        this.parentName2 = parentName2 == null ? null : parentName2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_student.school
     *
     * @return the value of res_student.school
     *
     * @mbg.generated
     */
    public String getSchool() {
        return school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_student.school
     *
     * @param school the value for res_student.school
     *
     * @mbg.generated
     */
    public void setSchool(String school) {
        this.school = school == null ? null : school.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_student.major
     *
     * @return the value of res_student.major
     *
     * @mbg.generated
     */
    public String getMajor() {
        return major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_student.major
     *
     * @param major the value for res_student.major
     *
     * @mbg.generated
     */
    public void setMajor(String major) {
        this.major = major == null ? null : major.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_student.grade
     *
     * @return the value of res_student.grade
     *
     * @mbg.generated
     */
    public String getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_student.grade
     *
     * @param grade the value for res_student.grade
     *
     * @mbg.generated
     */
    public void setGrade(String grade) {
        this.grade = grade == null ? null : grade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_student.clazz
     *
     * @return the value of res_student.clazz
     *
     * @mbg.generated
     */
    public String getClazz() {
        return clazz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_student.clazz
     *
     * @param clazz the value for res_student.clazz
     *
     * @mbg.generated
     */
    public void setClazz(String clazz) {
        this.clazz = clazz == null ? null : clazz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_student.content
     *
     * @return the value of res_student.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_student.content
     *
     * @param content the value for res_student.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_student.profession
     *
     * @return the value of res_student.profession
     *
     * @mbg.generated
     */
    public String getProfession() {
        return profession;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_student.profession
     *
     * @param profession the value for res_student.profession
     *
     * @mbg.generated
     */
    public void setProfession(String profession) {
        this.profession = profession == null ? null : profession.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_student
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", sex=").append(sex);
        sb.append(", age=").append(age);
        sb.append(", birthday=").append(birthday);
        sb.append(", roots=").append(roots);
        sb.append(", volk=").append(volk);
        sb.append(", code=").append(code);
        sb.append(", idCard=").append(idCard);
        sb.append(", political=").append(political);
        sb.append(", address=").append(address);
        sb.append(", tel=").append(tel);
        sb.append(", email=").append(email);
        sb.append(", parentTel=").append(parentTel);
        sb.append(", parentName1=").append(parentName1);
        sb.append(", parentName2=").append(parentName2);
        sb.append(", school=").append(school);
        sb.append(", major=").append(major);
        sb.append(", grade=").append(grade);
        sb.append(", clazz=").append(clazz);
        sb.append(", content=").append(content);
        sb.append(", profession=").append(profession);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}