package my.erp.org.mapper;

import java.util.List;

import my.erp.org.domain.Affiche;
import my.erp.org.vo.AfficheVo;

public interface AfficheMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_affiche
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_affiche
     *
     * @mbg.generated
     */
    int insert(Affiche record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_affiche
     *
     * @mbg.generated
     */
    int insertSelective(Affiche record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_affiche
     *
     * @mbg.generated
     */
    Affiche selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_affiche
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Affiche record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_affiche
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Affiche record);

	List<AfficheVo> queryAffiche(AfficheVo vo);
}