package my.erp.org.mapper;

import my.erp.org.domain.ApplyDepartment;

public interface ApplyDepartmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_apply_department
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_apply_department
     *
     * @mbg.generated
     */
    int insert(ApplyDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_apply_department
     *
     * @mbg.generated
     */
    int insertSelective(ApplyDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_apply_department
     *
     * @mbg.generated
     */
    ApplyDepartment selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_apply_department
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ApplyDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_apply_department
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ApplyDepartment record);

	int delApply(Long userId);
}