package my.erp.org.mapper;

import java.util.List;
import java.util.Map;

import my.erp.org.domain.Clazz;
import my.erp.org.vo.ClazzVo;

public interface ClazzMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_clazz
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_clazz
     *
     * @mbg.generated
     */
    int insert(Clazz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_clazz
     *
     * @mbg.generated
     */
    int insertSelective(Clazz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_clazz
     *
     * @mbg.generated
     */
    Clazz selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_clazz
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Clazz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_clazz
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Clazz record);
    
    List<ClazzVo> queryClazz(ClazzVo vo);

	List<Map<String, Object>> getClazzItem(Long id);
}