package my.erp.org.mapper;

import java.util.List;

import my.erp.org.domain.News;
import my.erp.org.vo.NewsVo;

public interface NewsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_news
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_news
     *
     * @mbg.generated
     */
    int insert(News record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_news
     *
     * @mbg.generated
     */
    int insertSelective(News record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_news
     *
     * @mbg.generated
     */
    News selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_news
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(News record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_news
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(News record);

	List<NewsVo> queryNews(NewsVo vo);

}