package my.erp.org.mapper;

import java.util.List;
import java.util.Map;

import my.erp.org.domain.Profession;
import my.erp.org.vo.ProfessionVo;

public interface ProfessionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_profession
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_profession
     *
     * @mbg.generated
     */
    int insert(Profession record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_profession
     *
     * @mbg.generated
     */
    int insertSelective(Profession record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_profession
     *
     * @mbg.generated
     */
    Profession selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_profession
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Profession record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_profession
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Profession record);

	List<ProfessionVo> queryProfession(ProfessionVo vo);

	List<Map<String, Object>> getProfessionItem();
}