package my.erp.org.mapper;

import java.util.List;

import my.erp.org.domain.Scheme;
import my.erp.org.vo.SchemeVo;

public interface SchemeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_scheme
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_scheme
     *
     * @mbg.generated
     */
    int insert(Scheme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_scheme
     *
     * @mbg.generated
     */
    int insertSelective(Scheme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_scheme
     *
     * @mbg.generated
     */
    Scheme selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_scheme
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Scheme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_scheme
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(Scheme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_scheme
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Scheme record);

	List<SchemeVo> queryScheme(SchemeVo vo);
}