package my.erp.org.domain;

import java.io.Serializable;

import my.erp.org.util.BasePo;

/**
 * Database Table Remarks:
 *   班级信息表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table res_clazz
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Clazz extends BasePo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_clazz.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   班级名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_clazz.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   班级人数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_clazz.num
     *
     * @mbg.generated
     */
    private Integer num;

    /**
     * Database Column Remarks:
     *   专业
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_clazz.major_id
     *
     * @mbg.generated
     */
    private Long majorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table res_clazz
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_clazz.id
     *
     * @return the value of res_clazz.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_clazz.id
     *
     * @param id the value for res_clazz.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_clazz.name
     *
     * @return the value of res_clazz.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_clazz.name
     *
     * @param name the value for res_clazz.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_clazz.num
     *
     * @return the value of res_clazz.num
     *
     * @mbg.generated
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_clazz.num
     *
     * @param num the value for res_clazz.num
     *
     * @mbg.generated
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_clazz.major_id
     *
     * @return the value of res_clazz.major_id
     *
     * @mbg.generated
     */
    public Long getMajorId() {
        return majorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_clazz.major_id
     *
     * @param majorId the value for res_clazz.major_id
     *
     * @mbg.generated
     */
    public void setMajorId(Long majorId) {
        this.majorId = majorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_clazz
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", num=").append(num);
        sb.append(", majorId=").append(majorId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}