package my.erp.org.domain;

import java.io.Serializable;
import java.util.Date;

import my.erp.org.util.BasePo;

/**
 * Database Table Remarks:
 *   部门信息表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table res_department
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Department extends BasePo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_department.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   部门名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_department.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   部门信息
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_department.info
     *
     * @mbg.generated
     */
    private String info;

    /**
     * Database Column Remarks:
     *   部门职责
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_department.duty
     *
     * @mbg.generated
     */
    private String duty;

    /**
     * Database Column Remarks:
     *   部门性质
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_department.characters
     *
     * @mbg.generated
     */
    private String characters;

    /**
     * Database Column Remarks:
     *   负责人姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_department.master_name
     *
     * @mbg.generated
     */
    private String masterName;

    /**
     * Database Column Remarks:
     *   负责人电话
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_department.master_tel
     *
     * @mbg.generated
     */
    private String masterTel;

    /**
     * Database Column Remarks:
     *   领导组织
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_department.lead_organize
     *
     * @mbg.generated
     */
    private String leadOrganize;

    /**
     * Database Column Remarks:
     *   成立时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_department.registration_time
     *
     * @mbg.generated
     */
    private String registrationTime;

    /**
     * Database Column Remarks:
     *   创始人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_department.registration_name
     *
     * @mbg.generated
     */
    private String registrationName;

    /**
     * Database Column Remarks:
     *   部门总人数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_department.num
     *
     * @mbg.generated
     */
    private Integer num;

    /**
     * Database Column Remarks:
     *   总则
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_department.general_rules
     *
     * @mbg.generated
     */
    private String generalRules;

    /**
     * Database Column Remarks:
     *   宗旨
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_department.purpose
     *
     * @mbg.generated
     */
    private String purpose;

    /**
     * Database Column Remarks:
     *   权利
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_department.droit
     *
     * @mbg.generated
     */
    private String droit;

    /**
     * Database Column Remarks:
     *   义务
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_department.obligation
     *
     * @mbg.generated
     */
    private String obligation;

    /**
     * Database Column Remarks:
     *   要求
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_department.requirement
     *
     * @mbg.generated
     */
    private String requirement;

    /**
     * Database Column Remarks:
     *   其他
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_department.other
     *
     * @mbg.generated
     */
    private String other;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_department.profession_id
     *
     * @mbg.generated
     */
    private Long professionId;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_department.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_department.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_department.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table res_department
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_department.id
     *
     * @return the value of res_department.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_department.id
     *
     * @param id the value for res_department.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_department.name
     *
     * @return the value of res_department.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_department.name
     *
     * @param name the value for res_department.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_department.info
     *
     * @return the value of res_department.info
     *
     * @mbg.generated
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_department.info
     *
     * @param info the value for res_department.info
     *
     * @mbg.generated
     */
    public void setInfo(String info) {
        this.info = info == null ? null : info.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_department.duty
     *
     * @return the value of res_department.duty
     *
     * @mbg.generated
     */
    public String getDuty() {
        return duty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_department.duty
     *
     * @param duty the value for res_department.duty
     *
     * @mbg.generated
     */
    public void setDuty(String duty) {
        this.duty = duty == null ? null : duty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_department.characters
     *
     * @return the value of res_department.characters
     *
     * @mbg.generated
     */
    public String getCharacters() {
        return characters;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_department.characters
     *
     * @param characters the value for res_department.characters
     *
     * @mbg.generated
     */
    public void setCharacters(String characters) {
        this.characters = characters == null ? null : characters.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_department.master_name
     *
     * @return the value of res_department.master_name
     *
     * @mbg.generated
     */
    public String getMasterName() {
        return masterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_department.master_name
     *
     * @param masterName the value for res_department.master_name
     *
     * @mbg.generated
     */
    public void setMasterName(String masterName) {
        this.masterName = masterName == null ? null : masterName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_department.master_tel
     *
     * @return the value of res_department.master_tel
     *
     * @mbg.generated
     */
    public String getMasterTel() {
        return masterTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_department.master_tel
     *
     * @param masterTel the value for res_department.master_tel
     *
     * @mbg.generated
     */
    public void setMasterTel(String masterTel) {
        this.masterTel = masterTel == null ? null : masterTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_department.lead_organize
     *
     * @return the value of res_department.lead_organize
     *
     * @mbg.generated
     */
    public String getLeadOrganize() {
        return leadOrganize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_department.lead_organize
     *
     * @param leadOrganize the value for res_department.lead_organize
     *
     * @mbg.generated
     */
    public void setLeadOrganize(String leadOrganize) {
        this.leadOrganize = leadOrganize == null ? null : leadOrganize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_department.registration_time
     *
     * @return the value of res_department.registration_time
     *
     * @mbg.generated
     */
    public String getRegistrationTime() {
        return registrationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_department.registration_time
     *
     * @param registrationTime the value for res_department.registration_time
     *
     * @mbg.generated
     */
    public void setRegistrationTime(String registrationTime) {
        this.registrationTime = registrationTime == null ? null : registrationTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_department.registration_name
     *
     * @return the value of res_department.registration_name
     *
     * @mbg.generated
     */
    public String getRegistrationName() {
        return registrationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_department.registration_name
     *
     * @param registrationName the value for res_department.registration_name
     *
     * @mbg.generated
     */
    public void setRegistrationName(String registrationName) {
        this.registrationName = registrationName == null ? null : registrationName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_department.num
     *
     * @return the value of res_department.num
     *
     * @mbg.generated
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_department.num
     *
     * @param num the value for res_department.num
     *
     * @mbg.generated
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_department.general_rules
     *
     * @return the value of res_department.general_rules
     *
     * @mbg.generated
     */
    public String getGeneralRules() {
        return generalRules;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_department.general_rules
     *
     * @param generalRules the value for res_department.general_rules
     *
     * @mbg.generated
     */
    public void setGeneralRules(String generalRules) {
        this.generalRules = generalRules == null ? null : generalRules.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_department.purpose
     *
     * @return the value of res_department.purpose
     *
     * @mbg.generated
     */
    public String getPurpose() {
        return purpose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_department.purpose
     *
     * @param purpose the value for res_department.purpose
     *
     * @mbg.generated
     */
    public void setPurpose(String purpose) {
        this.purpose = purpose == null ? null : purpose.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_department.droit
     *
     * @return the value of res_department.droit
     *
     * @mbg.generated
     */
    public String getDroit() {
        return droit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_department.droit
     *
     * @param droit the value for res_department.droit
     *
     * @mbg.generated
     */
    public void setDroit(String droit) {
        this.droit = droit == null ? null : droit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_department.obligation
     *
     * @return the value of res_department.obligation
     *
     * @mbg.generated
     */
    public String getObligation() {
        return obligation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_department.obligation
     *
     * @param obligation the value for res_department.obligation
     *
     * @mbg.generated
     */
    public void setObligation(String obligation) {
        this.obligation = obligation == null ? null : obligation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_department.requirement
     *
     * @return the value of res_department.requirement
     *
     * @mbg.generated
     */
    public String getRequirement() {
        return requirement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_department.requirement
     *
     * @param requirement the value for res_department.requirement
     *
     * @mbg.generated
     */
    public void setRequirement(String requirement) {
        this.requirement = requirement == null ? null : requirement.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_department.other
     *
     * @return the value of res_department.other
     *
     * @mbg.generated
     */
    public String getOther() {
        return other;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_department.other
     *
     * @param other the value for res_department.other
     *
     * @mbg.generated
     */
    public void setOther(String other) {
        this.other = other == null ? null : other.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_department.profession_id
     *
     * @return the value of res_department.profession_id
     *
     * @mbg.generated
     */
    public Long getProfessionId() {
        return professionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_department.profession_id
     *
     * @param professionId the value for res_department.profession_id
     *
     * @mbg.generated
     */
    public void setProfessionId(Long professionId) {
        this.professionId = professionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_department.create_time
     *
     * @return the value of res_department.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_department.create_time
     *
     * @param createTime the value for res_department.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_department.update_time
     *
     * @return the value of res_department.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_department.update_time
     *
     * @param updateTime the value for res_department.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_department.status
     *
     * @return the value of res_department.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_department.status
     *
     * @param status the value for res_department.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_department
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", info=").append(info);
        sb.append(", duty=").append(duty);
        sb.append(", characters=").append(characters);
        sb.append(", masterName=").append(masterName);
        sb.append(", masterTel=").append(masterTel);
        sb.append(", leadOrganize=").append(leadOrganize);
        sb.append(", registrationTime=").append(registrationTime);
        sb.append(", registrationName=").append(registrationName);
        sb.append(", num=").append(num);
        sb.append(", generalRules=").append(generalRules);
        sb.append(", purpose=").append(purpose);
        sb.append(", droit=").append(droit);
        sb.append(", obligation=").append(obligation);
        sb.append(", requirement=").append(requirement);
        sb.append(", other=").append(other);
        sb.append(", professionId=").append(professionId);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", status=").append(status);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}